# See https://pre-commit.com for more information
---
ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482  # frozen: v2.2.6
    hooks:
    - id: codespell
      # Additional dependency needed until Python 3.11 is our minimum version.
      additional_dependencies:
        - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: c22645f6b45188216151a407c040a9eec1795ab0  # frozen: v0.3.3
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10240']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        # Prevent PP files being inappropriately "fixed".
        exclude: ^.+\.pp$
      - id: trailing-whitespace
