# See https://pre-commit.com for more information
---
ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 75d1925b523dd109cc200d1b29142ff36ec785ad  # frozen: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482  # frozen: v2.2.6
    hooks:
    - id: codespell
      # Additional dependency needed until Python 3.11 is our minimum version.
      additional_dependencies:
        - tomli

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 34974913abb598ee76541db1900f24fde7dd1d76  # frozen: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10240']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        # Prevent PP files being inappropriately "fixed".
        exclude: ^.+\.pp$
      - id: trailing-whitespace
