name: cset-workflow-dev
channels:
  - conda-forge
dependencies:
  # Runtime dependencies
  - cset >= 0.4.0
  - pip >= 23.1

  # Development dependencies
  - pre-commit
  - black

  # Documentation dependencies
  - sphinx >= 6.0
  - furo
