name: cset-run
channels:
  - conda-forge
dependencies:
  # Runtime dependencies
  - numpy
  - iris >= 3.5
  - ruamel.yaml >= 0.17
  - mo_pack # For handling pp files.
  - pygraphviz
  - isodate

  # Build dependencies
  - setuptools>=61.0
  - pip

  # Development dependencies
  - pre-commit
  - black

  # Testing dependencies
  - tox < 4.0
  - tox-conda
  - pytest >= 7.0
  - pytest-cov

  # Documentation dependencies
  - sphinx >= 6.0
  - furo
