name: Publish packages

on:
  release:
    types: [released]

# Allow only one concurrent deployment
concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
            python-version: "3.x"

      - name: Install dependencies
        run: python3 -m pip install tox tox-conda

      # - uses: actions/cache@v3
      #   with:
      #       key: tox|build-package|${{ runner.os }}-${{ runner.arch}}|${{ hashFiles('requirements/locks/*') }}
      #       path: .tox

      - name: Build package
        run: tox -e build-package

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/
          retention-days: 10
          if-no-files-found: error

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-package
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/

      - name: List files
        run: ls -RA

      # External actions are disabled via organization policies therefore we
      # must instead manually implement it.
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/#the-manual-way
      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/

      - uses: actions/setup-python@v4
        with:
            python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install twine

      - name: Check package metadata
        run: python -m twine check --strict dist/*

      - name: mint API token
        id: mint-token
        run: |
          # retrieve the ambient OIDC token
          resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=pypi")
          oidc_token=$(jq '.value' <<< "${resp}")

          # exchange the OIDC token for an API token
          resp=$(curl -X POST https://pypi.org/_/oidc/github/mint-token -d "{\"token\": \"${oidc_token}\"}")
          api_token=$(jq '.token' <<< "${resp}")

          # mask the newly minted API token, so that we don't accidentally leak it
          echo "::add-mask::${api_token}"

          # see the next step in the workflow for an example of using this step output
          echo "api-token=${api_token}" >> "${GITHUB_OUTPUT}"

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ steps.mint-token.outputs.api-token }}
          TWINE_REPOSITORY: testpypi
        run: python3 -m twine upload --non-interactive dist/*
